[Distribution]
Distribution=fedora
Release=44
Architecture=arm64

[Output]
Format=directory
Output=mkosi.rootfs
Bootable=no

[Content]
RootPassword=fedora
WithDocs=True
Environment=
    KERNEL_INSTALL_BYPASS=0
Packages=
    @core
    abattis-cantarell-vf-fonts
    acl
    adobe-source-code-pro-fonts
    avahi
    bash-completion
    binutils
    bluez
    btop
    chrony
    cloud-utils-growpart
    cracklib
    cracklib-dicts
    default-fonts-core-sans
    dhcp-client
    diffutils
    dnf-plugins-core
    dosfstools
    dracut
    efivar
    fastfetch
    findutils
    firefox
    fish
    flatpak
    git
    glib-networking
    glibc-all-langpacks
    google-carlito-fonts
    google-crosextra-caladea-fonts
    google-droid-sans-fonts
    google-noto-color-emoji-fonts
    google-noto-fonts-common
    google-noto-sans-mono-vf-fonts
    google-noto-sans-vf-fonts
    google-noto-serif-vf-fonts
    iso-codes
    java-latest-openjdk
    kmod
    langpacks-fonts-en
    liberation-mono-fonts
    liberation-sans-fonts
    liberation-serif-fonts
    librsvg2
    libsane-hpaio
    light
    linux-firmware
    localsearch
    man-pages
    mesa-dri-drivers
    mesa-libEGL
    nano
    net-tools
    NetworkManager-adsl
    NetworkManager-ppp
    NetworkManager-tui
    NetworkManager-wifi
    NetworkManager-wwan
    nodejs-npm
    open-sans-fonts
    openssl
    passwd
    pciutils
    pipa-kernel-flasher-hook
    pipa-metapkg
    pipewire
    pipewire-pulseaudio
    plymouth-theme-spinner
    polkit
    rsync
    rygel
    sane-backends-drivers-scanners
    systemd-oomd-defaults
    systemd-pam
    tar
    tinysparql
    tuned
    tuned-ppd
    unzip
    usbutils
    vim-enhanced
    vim-minimal
    wget
    widevine-installer
    wpa_supplicant
    xdg-desktop-portal
    xdg-user-dirs
    zenity
    zram-generator
