[Content]
Packages=
    cliphist
    dms
    dms-greeter
    dsearch
    eog
    ghostty
    gnome-keyring
    gnome-text-editor
    mako
    matugen
    nautilus
    niri
    seahorse
    wl-clipboard
    xdg-desktop-portal
    xdg-desktop-portal-gnome
    xdg-desktop-portal-gtk
    xwayland-satellite
