[Content]
Packages=
    dms
    dms-greeter
    eog
    gdm
    gnome-text-editor
    mako
    nautilus
    niri
    polkit polkit-gnome
    seahorse
    xdg-desktop-portal
    xdg-desktop-portal-gnome
    xdg-desktop-portal-gtk
