[Content]
Packages=
    dms
    dms-greeter
    eog
    sddm
    gnome-text-editor
    mako
    nautilus
    niri
    polkit
    seahorse
    swaybg
    xdg-desktop-portal
    xdg-desktop-portal-gnome
    xdg-desktop-portal-gtk
