[Content]
Packages=
    NetworkManager-openconnect-gnome
    NetworkManager-openvpn-gnome
    NetworkManager-pptp-gnome
    NetworkManager-ssh-gnome
    NetworkManager-vpnc-gnome
    adwaita-mono-fonts
    adwaita-sans-fonts
    default-fonts-core-emoji
    default-fonts-core-sans
    dhcp-client
    eog
    gnome-backgrounds
    gnome-bluetooth
    gnome-browser-connector
    gnome-calculator
    gnome-clocks
    gnome-color-manager
    gnome-control-center
    gnome-disk-utility
    gnome-epub-thumbnailer
    gnome-initial-setup
    gnome-remote-desktop
    gnome-session-wayland-session
    gnome-settings-daemon
    gnome-shell
    gnome-software
    gnome-text-editor
    gvfs-afc
    gvfs-afp
    gvfs-archive
    gvfs-fuse
    gvfs-goa
    gvfs-gphoto2
    gvfs-mtp
    gvfs-smb
    iproute
    iputils
    mesa-dri-drivers
    nautilus
    phoc
    phosh
    ptyxis
    seahorse
    sushi
    wpa_supplicant

