[Content]
Packages=
    NetworkManager-openconnect-gnome
    NetworkManager-openvpn-gnome
    NetworkManager-pptp-gnome
    NetworkManager-ssh-gnome
    NetworkManager-vpnc-gnome
    adwaita-mono-fonts
    adwaita-sans-fonts
    default-fonts-core-emoji
    default-fonts-core-sans
    dhcp-client
    eog
    gnome-backgrounds
    gnome-browser-connector
    gnome-calculator
    gnome-clocks
    gnome-disk-utility
    gnome-epub-thumbnailer
    gnome-initial-setup
    gnome-settings-daemon
    gnome-software
    gnome-text-editor
    gvfs-afc
    gvfs-afp
    gvfs-archive
    gvfs-fuse
    gvfs-goa
    gvfs-gphoto2
    gvfs-mtp
    gvfs-smb
    iproute
    iputils
    mesa-dri-drivers
    nautilus
    phoc
    phosh
    phosh-tour
    phosh-mobile-settings
    ptyxis
    seahorse
    stevia-phosh-osk-provider
    sushi
    wpa_supplicant
