[Content]
Packages=
    @kde-mobile
    bluedevil
    dolphin
    elisa-player
    kate
    kpipewire
    kde-gtk-config
    haruna
    kalk
    kclock
    okular-mobile
    plasma-login-manager
    plasma-nm
    plasma-nm-l2tp
    plasma-nm-openconnect
    plasma-nm-openswan
    plasma-nm-openvpn
    plasma-nm-pptp
    plasma-nm-vpnc
    powerdevil
    qmlkonsole
    upower
