[Content]
Packages=
    ark
    bluedevil
    breeze-gtk
    breeze-icon-theme
    dolphin
    gwenview
    kate
    kde-gtk-config
    kde-partitionmanager
    kdegraphics-thumbnailers
    kf6-krunner
    plasma-milou
    kinfocenter
    kio-extras
    konsole
    kpipewire
    kscreen
    kscreenlocker
    kwalletmanager
    kwin
    okular
    pam-kwallet
    pinentry-qt
    plasma-breeze-common
    plasma-breeze-qt5
    plasma-breeze-qt6
    plasma-desktop
    plasma-discover
    plasma-discover-flatpak
    plasma-login-manager
    plasma-nm
    plasma-nm-l2tp
    plasma-nm-openconnect
    plasma-nm-openswan
    plasma-nm-openvpn
    plasma-nm-pptp
    plasma-nm-vpnc
    plasma-pa
    plasma-setup
    plasma-workspace
    plasma-workspace-wayland
    polkit-kde
    powerdevil
    qmlkonsole
    upower
    xdg-desktop-portal-kde
    xdg-user-dirs
    xdg-user-dirs-gtk
