name: Build Editions install packages

permissions:
  contents: write

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v6

    - name: Build the Docker image
      run: docker build . -t 'pipa-fedora-builder'

    - name: Build the Workstation image
      run: docker run --privileged -v "$(pwd)"/images:/build/images -v "/dev:/dev" pipa-fedora-builder workstation

    - name: Build the KDE Plasma Edition image
      run: docker run --privileged -v "$(pwd)"/images:/build/images -v "/dev:/dev" pipa-fedora-builder plasma-edition

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2.6.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: f44-${{ steps.date.outputs.date }}
        name: Fedora 44 ${{ steps.date.outputs.date }}
        files: images/*.zip
        draft: true
